### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Qasimmodo** [m0rtem/CloudFail#1]
root@e:~/CloudFuck# python3 cf.py seo.com
Traceback (most recent call last):
  File "cf.py", line 5, in <module>
    from DNSDumpsterAPI import DNSDumpsterAPI
  File "/root/CloudFuck/DNSDumpsterAPI.py", line 8, in <module>
    import requests
ImportError: No module named 'requests'
root@e:~/CloudFuck#

**Comment by m0rtem** [comment]
seems like you need the requests module;

what happens if you try:

> sudo pip install requests

**Comment by Qasimmodo** [comment]
Hey, sorry for the late reply, I git clone'd again, getting this error after I... sudo pip install colorama.

root@e:[~/CloudFail]: python cloudfail.py --target seo.com
Traceback (most recent call last):
  File "cloudfail.py", line 9, in <module>
    import colorama

**Comment by m0rtem** [comment]
Yo that cool sorry for the close thought that fixed it.

I pushed quite a big update in the mean time, but the libs should had stayed the same.

You definitely are running on python3? You may need to set this up if you are using Linux.

also please make sure you have the colorama lib here: https://pypi.python.org/pypi/colorama

**Comment by m0rtem** [comment]
Closing due to no reply

**Comment by wifiuk** [comment]
i get the colorama issue also

**Comment by m0rtem** [comment]
@wifiuk you need to install colorama for python3 `sudo pip3 install colorama`

You will need pip setup correctly for python3 (pip3)

**Comment by dheeraj750** [comment]
`   ____ _                 _ _____     _ _
  / ___| | ___  _   _  __| |  ___|_ _(_) |                                                                                                                         
 | |   | |/ _ \| | | |/ _` | |_ / _` | | |                                                                                                                         
 | |___| | (_) | |_| | (_| |  _| (_| | | |                                                                                                                         
  \____|_|\___/ \__,_|\__,_|_|  \__,_|_|_|                                                                                                                         
    v1.0.5                      by m0rtem                                                                                                                          
                                                                                                                                                                   
                                                                                                                                                                 
  File "/home/dheeraj/Desktop/tools/CloudFail/cloudfail.py", line 307, in <module>
    dnsdumpster(args.target)
  File "/home/dheeraj/Desktop/tools/CloudFail/cloudfail.py", line 84, in dnsdumpster
    res = DNSDumpsterAPI(False).search(target)
  File "/home/dheeraj/Desktop/tools/CloudFail/DNSDumpsterAPI.py", line 71, in search
    soup = BeautifulSoup(req.content, 'html.parser')
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/usr/local/lib/python3.10/dist-packages/bs4/builder/_htmlparser.py", line 215, in feed
    parser.feed(markup)
  File "/usr/lib/python3.10/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.10/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
  File "/usr/lib/python3.10/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/usr/local/lib/python3.10/dist-packages/bs4/builder/_htmlparser.py", line 160, in handle_decl
    self.soup.endData(Doctype)
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1054, in __getattr__
    return self.find(tag)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1292, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1313, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1610, in __init__
    self.text = self._normalize_search_value(text)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1615, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
AttributeError: module 'collections' has no attribute 'Callable'
`
