### ISSUE TITLE
i have some error AttributeError: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by Zibzeus** [m0rtem/CloudFail#106]
hi, can u help me to finish this problem sir ?

i give some error log in here : 
Traceback (most recent call last):
  File "/home/smartcapt/Downloads/KP/CloudFail/cloudfail.py", line 307, in <module>
    dnsdumpster(args.target)
  File "/home/smartcapt/Downloads/KP/CloudFail/cloudfail.py", line 84, in dnsdumpster
    res = DNSDumpsterAPI(False).search(target)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smartcapt/Downloads/KP/CloudFail/DNSDumpsterAPI.py", line 71, in search
    soup = BeautifulSoup(req.content, 'html.parser')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 215, in feed
    parser.feed(markup)
  File "/usr/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.11/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/builder/_htmlparser.py", line 160, in handle_decl
    self.soup.endData(Doctype)
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/element.py", line 1054, in __getattr__
    return self.find(tag)
           ^^^^^^^^^^^^^^
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/element.py", line 1292, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/element.py", line 1313, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/element.py", line 1610, in __init__
    self.text = self._normalize_search_value(text)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/smartcapt/.local/lib/python3.11/site-packages/bs4/element.py", line 1615, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
                                                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by xhat007** [comment]
Please ensure that you are using Python version 3.9 or 3.8 for this project, as versions 3.10 and 3.11 are not supported.
