### ISSUE TITLE
ModuleNotFoundError: No module named 'win inet pton'

### ISSUE THREAD

**Issue by trollmad3** [m0rtem/CloudFail#26]
I installed everything correctly but when I try to resolve a website I get this:

`Traceback (most recent call last) : `
`File "cloudfail.py", line 13, in <module>`
`import win_inet_pton `
`ModuleNotFoundError: No module named 'win inet pton' `

Photo: 
![image](https://user-images.githubusercontent.com/7843719/38647651-a5b31768-3daa-11e8-8ddf-d4dced68ee3a.png)

**Comment by m0rtem** [comment]
Hmm, seems you dont have the win inet python package installed.

Try to run:

`pip3 install win_inet_pton`

**Comment by trollmad3** [comment]
@m0rtem Did that and it says `ImportError: Entry point ('console_scripts', 'pip3') not found` (same thing with the other issue)

**Comment by pantami** [comment]
pip install BeautifulSoup4 

or 

pip3 install BeautifulSoup4

**Comment by Ba5h3r** [comment]
You ran` pip install -r requirements.txt `and installed it for py2, like I just did, a second ago.
if you use `pip3 install -r requirements.txt` it works perfectly, a m0rtem correctly suggested.

**Comment by trollmad3** [comment]
@Ba5h3r Thanks.

**Comment by Jihadist** [comment]
Arch is here now
`(base) [net_client@netarchwork CloudFail]$ python3 cloudfail.py 
Traceback (most recent call last):
  File "cloudfail.py", line 13, in <module>
    import win_inet_pton
ModuleNotFoundError: No module named 'win_inet_pton'
(base) [net_client@netarchwork CloudFail]$ sudo pip3 install win_inet_pton
Requirement already satisfied: win_inet_pton in /usr/lib/python3.7/site-packages (1.0.1)
`
What's wrong ? Thanx

**Comment by saikiran994** [comment]
pip install win_inet_pton or pip install win-inet-pton

**Comment by jerrygems** [comment]
┌─[✗]─[sp1d3y@parrot]─[~/bbh-tools/CloudFail]
└──╼ $python3 cloudfail.py --target replaced_for_some_reason --tor
   ____ _                 _ _____     _ _
  / ___| | ___  _   _  __| |  ___|_ _(_) |
 | |   | |/ _ \| | | |/ _` | |_ / _` | | |
 | |___| | (_) | |_| | (_| |  _| (_| | | |
  \____|_|\___/ \__,_|\__,_|_|  \__,_|_|_|
    v1.0.5                      by m0rtem


[10:10:38] Initializing CloudFail - the date is: 21/12/2022  
Traceback (most recent call last):
  File "/home/sp1d3y/bbh-tools/CloudFail/socks.py", line 732, in connect
    _BaseSocket.connect(self, proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
  File "/home/sp1d3y/bbh-tools/CloudFail/socks.py", line 743, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1e29e9f4f0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e29e9f4f0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sp1d3y/bbh-tools/CloudFail/cloudfail.py", line 288, in <module>
    tor_ip = requests.get(ipcheck_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1e29e9f4f0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sp1d3y/bbh-tools/CloudFail/cloudfail.py", line 295, in <module>
    print(e, net_exc)
NameError: name 'net_exc' is not defined
