### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by duzun** [m0rtem/CloudFail#30]
```sh
python3 cloudfail.py -t cdn.duzun.me
```

```
There was an error getting results
Traceback (most recent call last):
  File "cloudfail.py", line 285, in <module>
    dnsdumpster(args.target)
  File "cloudfail.py", line 84, in dnsdumpster
    if res['dns_records']['host']:
TypeError: list indices must be integers or slices, not str
```

**Comment by m0rtem** [comment]
Hi thanks for reporting,

can you confirm it is resolved in commit https://github.com/m0rtem/CloudFail/commit/a2ac2e075bb10d67d68d72c15309cd6efe4be71e for me please?

**Comment by Uonlylivetwice** [comment]
Hi @m0rtem!
`python3 cloudfail.py -t codeby.net  `
`[16:28:53] Testing for misconfigured DNS using dnsdumpster...  
There was an error getting results
Traceback (most recent call last):
  File "/Users/amur/CloudFail/cloudfail.py", line 312, in <module>
    dnsdumpster(args.target)
  File "/Users/amur/CloudFail/cloudfail.py", line 86, in dnsdumpster
    if res['dns_records']['host']:
TypeError: list indices must be integers or slices, not str`
