### ISSUE TITLE
run error when add --tor

### ISSUE THREAD

**Issue by iepngs** [m0rtem/CloudFail#44]
```shell
[14:01:42] Initializing CloudFail - the date is: 13/10/2020
Traceback (most recent call last):
  File "/root/CloudFail/socks.py", line 729, in connect
    _BaseSocket.connect(self, proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
  File "/root/CloudFail/socks.py", line 740, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd1c825b208>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests-2.24.0-py3.6.egg/requests/adapters.py", line 449, in send           timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='canihazip.com', port=80): Max retries exceeded with url: /s (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1c825b208>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cloudfail.py", line 293, in <module>
    tor_ip = requests.get(ipcheck_url)
  File "/usr/local/lib/python3.6/dist-packages/requests-2.24.0-py3.6.egg/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests-2.24.0-py3.6.egg/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests-2.24.0-py3.6.egg/requests/sessions.py", line 530, in request        resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests-2.24.0-py3.6.egg/requests/sessions.py", line 643, in send           r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests-2.24.0-py3.6.egg/requests/adapters.py", line 516, in send           raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='canihazip.com', port=80): Max retries exceeded with url: /s (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1c825b208>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cloudfail.py", line 300, in <module>
    print(e, net_exc)
NameError: name 'net_exc' is not defined
```

**Comment by m0rtem** [comment]
check your local SOCKS5 proxy on 127.0.0.1:9050, it is probably not listening / running.

**Comment by Bewarzx1** [comment]
I need help I think my socket not working can u help 
![Uploading image.jpg…]()
