### ISSUE TITLE
could not complete execution 

### ISSUE THREAD

**Issue by braunwalker** [m0rtem/CloudFail#47]
hey im gettin this error

kaliuser@kaliuser:/CloudFail$ python3 cloudfail.py --target seo.com
cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
   ____ _                 _ _____     _ _
  / ___| | ___  _   _  __| |  ___|_ _(_) |
 | |   | |/ _ \| | | |/ _` | |_ / _` | | |
 | |___| | (_) | |_| | (_| |  _| (_| | | |
  \____|_|\___/ \__,_|\__,_|_|  \__,_|_|_|
    v1.0.2                      by m0rtem

[11:24:00] Initializing CloudFail - the date is: 02/12/2020
[11:24:00] Fetching initial information from: seo.com...
[11:24:00] No ipout file found, fetching data
[11:24:00] Just checking for updates, please wait...
[11:24:00] Updating CloudFlare subnet...
Traceback (most recent call last):
  File "cloudfail.py", line 309, in <module>
    init(args.target)
  File "cloudfail.py", line 138, in init
    update()
  File "cloudfail.py", line 246, in update
    with open('data/cf-subnet.txt', 'wb') as fd:
PermissionError: [Errno 13] Permission denied: 'data/cf-subnet.txt'

**Comment by dogukank1l1c** [comment]
![image](https://user-images.githubusercontent.com/73218416/131363716-e36ec307-7f79-428a-99c0-02fe1ee9aea5.png)

**Comment by LP-H4cmilo** [comment]
> 

try to run the script as sudo
it should fix the issue

**Comment by LP-H4cmilo** [comment]
> ![image](https://user-images.githubusercontent.com/73218416/131363716-e36ec307-7f79-428a-99c0-02fe1ee9aea5.png) Same ...

try to install the python3 component by using this command
`sudo pip3 install win_inet_pton`

it should fix it

**Comment by elitetradesman** [comment]
tried both still the same
