### ISSUE TITLE
Failed to establish a new connection: [Errno 111]

### ISSUE THREAD

**Issue by migliori** [m0rtem/CloudFail#51]
Hi,

I tried a simple command with `python3 cloudfail.py --target ` but it fails, here's a copy:

```[10:25:17] Initializing CloudFail - the date is: 16/04/2021
[10:25:17] Fetching initial information from: themebanks.com...
[10:25:17] No ipout file found, fetching data
[10:25:17] Just checking for updates, please wait...
[10:25:17] Updating CloudFlare subnet...
[10:25:17] Updating Crimeflare database...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f90fa9ed4e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90fa9ed4e0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cloudfail.py", line 309, in <module>
    init(args.target)
  File "cloudfail.py", line 138, in init
    update()
  File "cloudfail.py", line 252, in update
    r = requests.get("http://crimeflare.net:83/domains/ipout.zip", stream=True)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f90fa9ed4e0>: Failed to establish a new connection: [Errno 111] Connection refused',))```

Thanks for your help

**Comment by paoloaq** [comment]
Same issue here ... :(
Is the project dead?

**Comment by mantacid** [comment]
I'm having the same issue. I doubt the project is dead. My guess is that some API key is misconfigured. I'll see what I can find.

**Comment by mantacid** [comment]
Looking up crimeflare showed that the sites are no longer up. I'm not surprised; putting the site that circumvents cloudflare behind cloudflare was bound to piss them off.
