### ISSUE TITLE
Tor rejects connection "anonymous" socks from CloudFail.

### ISSUE THREAD

**Issue by HAE** [m0rtem/CloudFail#52]
Whenever I run the tool using [--tor] option, I get multiple socks related errors as follows:

```
python3 cloudfail.py --target domainx.com --tor

[21:41:25] Initializing CloudFail - the date is: 18/04/2021
Traceback (most recent call last):
  File "C:\Security\programs\cloudfail\socks.py", line 747, in connect
    negotiate(self, dest_addr, dest_port)
  File "C:\Security\programs\cloudfail\socks.py", line 419, in _negotiate_SOCKS5
    CONNECT, dest_addr)
  File "C:\Security\programs\cloudfail\socks.py", line 494, in _SOCKS5_request
    raise SOCKS5Error("{0:#04x}: {1}".format(status, error))
socks.SOCKS5Error: 0x01: General SOCKS server failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
  File "C:\Security\programs\cloudfail\socks.py", line 751, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: 0x01: General SOCKS server failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x041F2C70>: Failed to establish a new connection: Socket error: 0x01: General SOCKS server failure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041F2C70>: Failed to establish a new connection: Socket error: 0x01: General SOCKS server failure'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cloudfail.py", line 293, in <module>
    tor_ip = requests.get(ipcheck_url)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\UserX\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041F2C70>: Failed to establish a new connection: Socket error: 0x01: General SOCKS server failure'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cloudfail.py", line 300, in <module>
    print(e, net_exc)
NameError: name 'net_exc' is not defined
```

Here is the corresponding error that the Tor proxy spits out.

`[warn] Rejecting SOCKS request for anonymous connection to private address [scrubbed]. [3 similar message(s) suppressed in last 10 seconds]
`

I'm Using:
Cygwin in Windows 8.1 with Python3 and Tor v0.3.5.7 (which otherwise works without any issues)
Both the Tor socks[port:9050] and http[port:8118] are enabled.

When using the CloudFail without the Tor proxy it seems to work OK. Any hint what needs to be done to make Tor accept the connections?

**Comment by m0rtem** [comment]
I have not had any time to keep the tor connectoin part of this project updated so I cannot help with this right now
