### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Uonlylivetwice** [m0rtem/CloudFail#56]
Hi @m0rtem!
python3 cloudfail.py -u -t codeby.net 
[16:28:53] Testing for misconfigured DNS using dnsdumpster... There was an error getting results Traceback (most recent call last): File "/Users/amur/CloudFail/cloudfail.py", line 312, in <module> dnsdumpster(args.target) File "/Users/amur/CloudFail/cloudfail.py", line 86, in dnsdumpster if res['dns_records']['host']: TypeError: list indices must be integers or slices, not str
 @Uonlylivetwice

Write

**Comment by thistehneisen** [comment]
Having the exact same problem for last 48 hours.

**Comment by m0rtem** [comment]
this should be fixed now

**Comment by Uonlylivetwice** [comment]
> this should be fixed now
`amur@A-Mur CloudFail % python3 cloudfail.py -u -t codeby.net
/Users/amur/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/Users/amur/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/Users/amur/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
[13:39:18] Initializing CloudFail - the date is: 30/07/2021  
[13:39:18] Just checking for updates, please wait...  
[13:39:18] Updating CloudFlare subnet...  
[13:39:19] Updating Crimeflare database...  
[13:40:16] Fetching initial information from: codeby.net...  
[13:40:16] Server IP: 104.26.0.76  
[13:40:16] Testing if codeby.net is on the Cloudflare network...  
[13:40:16] codeby.net is part of the Cloudflare network!  
[13:40:16] Testing for misconfigured DNS using dnsdumpster...  
There was an error getting results
Traceback (most recent call last):
  File "/Users/amur/CloudFail/cloudfail.py", line 312, in <module>
    dnsdumpster(args.target)
  File "/Users/amur/CloudFail/cloudfail.py", line 86, in dnsdumpster
    if res['dns_records']['host']:
TypeError: list indices must be integers or slices, not str`

**Comment by m0rtem** [comment]
did you even bother to pull down the changes?

**Comment by Uonlylivetwice** [comment]
> did you even bother to pull down the changes?

don't understand what changes u r talking about...
