### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by qimuo** [m0rtem/CloudFail#61]
/root/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
Traceback (most recent call last):
  File "/root/cloudfail.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
root@localhost:~# python3 cloudfail.py --target seo.com
/root/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
Traceback (most recent call last):
  File "/root/cloudfail.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
root@localhost:~# python3 cloudfail.py --target seo.com
/root/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
Traceback (most recent call last):
  File "/root/cloudfail.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
root@localhost:~# python3 cloudfail.py --target seo.com
/root/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
Traceback (most recent call last):
  File "/root/cloudfail.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by markiemm** [comment]
> I am having the same issue even after running pip3 inside cloudfail folder

Did you do the step above ^

**Comment by immortalsolitude** [comment]
> Yes followed the same steps and ran requirements.txt inside the cloudfail folder
root@kali:~# cd Desktop/
root@kali:~/Desktop# ls
 autogrid.txt     cloudfail  'Cookie 1'                request       straightbroker       test.jpg   test,txt   test.txt.jpg   XXS
 clickjack.html   COMMANDS    LogsAndDiagnostics.zip   request.txt   straightbroker.txt   test.php   test.txt   wordlists      Yukichan
root@kali:~/Desktop# cd cloudfail/
root@kali:~/Desktop/cloudfail# 
root@kali:~/Desktop/cloudfail# 
root@kali:~/Desktop/cloudfail# ls
CloudFail
root@kali:~/Desktop/cloudfail# cd CloudFail/
root@kali:~/Desktop/cloudfail/CloudFail# ls
cloudfail.py  data  DNSDumpsterAPI.py  Dockerfile  LICENSE.md  __pycache__  README.md  requirements.txt  sockshandler.py  socks.py
root@kali:~/Desktop/cloudfail/CloudFail# pip3 install -r requirements.txt
Requirement already satisfied: beautifulsoup4==4.6.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 1)) (4.6.0)
Requirement already satisfied: bs4==0.0.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: certifi==2017.4.17 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (2017.4.17)
Requirement already satisfied: chardet==3.0.4 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: colorama==0.3.9 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (0.3.9)
Requirement already satisfied: idna==2.5 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 6)) (2.5)
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.25.1)
Requirement already satisfied: urllib3==1.24.2 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (1.24.2)
Requirement already satisfied: win_inet_pton==1.0.1 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 9)) (1.0.1)
Requirement already satisfied: dnspython==1.15.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 10)) (1.15.0)

root@kali:~/Desktop/cloudfail/CloudFail# python3 cloudfail.py --target seo.com --tor
/root/Desktop/cloudfail/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/Desktop/cloudfail/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/Desktop/cloudfail/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
   ____ _                 _ _____     _ _
  / ___| | ___  _   _  __| |  ___|_ _(_) |
 | |   | |/ _ \| | | |/ _` | |_ / _` | | |
 | |___| | (_) | |_| | (_| |  _| (_| | | |
  \____|_|\___/ \__,_|\__,_|_|  \__,_|_|_|
    v1.0.3                      by m0rtem


[09:42:29] Initializing CloudFail - the date is: 01/11/2021  
Traceback (most recent call last):
  File "/root/Desktop/cloudfail/CloudFail/socks.py", line 729, in connect
    _BaseSocket.connect(self, proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
  File "/root/Desktop/cloudfail/CloudFail/socks.py", line 740, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb254226190>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb254226190>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Desktop/cloudfail/CloudFail/cloudfail.py", line 293, in <module>
    tor_ip = requests.get(ipcheck_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb254226190>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Desktop/cloudfail/CloudFail/cloudfail.py", line 300, in <module>
    print(e, net_exc)
NameError: name 'net_exc' is not defined


> 
> > I am having the same issue even after running pip3 inside cloudfail folder
> 
> Did you do the step above ^

Yes followed the exact steps

**Comment by markiemm** [comment]
> Yes followed the exact steps

Looking at your log you have all modules installed and you ran the ``--tor`` argument. In order to scan a target using Tor, You have to have a tor service running ``service tor start`` (must have it installed). Not running the ``--tor`` argument will work.

**Comment by markiemm** [comment]
Are you behind a proxy or VPN?

**Comment by markiemm** [comment]
> Neither...

Ok so I cloned the repo and ran the same command and concluded that Crimeflare is not up so it coulden't update the crimeflare database. It's not your issue

**Comment by elitetradesman** [comment]
I installed correctly running (pip3 install -r requirements.txt) and still this is what i get 
/home/elite/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/elite/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/elite/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
   ____ _                 _ _____     _ _
  / ___| | ___  _   _  __| |  ___|_ _(_) |                            
 | |   | |/ _ \| | | |/ _` | |_ / _` | | |                            
 | |___| | (_) | |_| | (_| |  _| (_| | | |                            
  \____|_|\___/ \__,_|\__,_|_|  \__,_|_|_|                            
    v1.0.3                      by m0rtem                             
                                                                      
                                                                      
[01:06:29] Initializing CloudFail - the date is: 07/03/2022  
[01:06:29] Just checking for updates, please wait...  
[01:06:29] Updating CloudFlare subnet...  
[01:06:29] Updating Crimeflare database...  
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff50dce1940>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff50dce1940>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/elite/CloudFail/cloudfail.py", line 304, in <module>
    update()
  File "/home/elite/CloudFail/cloudfail.py", line 252, in update
    r = requests.get("http://crimeflare.net:83/domains/ipout.zip", stream=True)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff50dce1940>: Failed to establish a new connection: [Errno 110] Connection timed out'))

PLEASE HELP TROUBLESHOOT

**Comment by zidansec** [comment]
Anyone know why this happened?

```bash
/home/zidan/Tools/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/zidan/Tools/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/zidan/Tools/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/zidan/Tools/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/zidan/Tools/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
Traceback (most recent call last):
  File "/home/zidan/Tools/CloudFail/cloudfail.py", line 9, in <module>
    import socks
  File "/home/zidan/Tools/CloudFail/socks.py", line 62, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by blackhatethicalhacking** [comment]
Same error as @zidansec even after pip3 install Callable

**Comment by IsekaiGuy** [comment]
> Anyone know why this happened?
> 
> ```shell
> /home/zidan/Tools/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   while choice is not 'y' and choice is not 'n':
> /home/zidan/Tools/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   while choice is not 'y' and choice is not 'n':
> /home/zidan/Tools/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   while choice is not 'y' and choice is not 'n':
> /home/zidan/Tools/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
>   while choice is not 'y' and choice is not 'n':
> /home/zidan/Tools/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if choice is 'y':
> Traceback (most recent call last):
>   File "/home/zidan/Tools/CloudFail/cloudfail.py", line 9, in <module>
>     import socks
>   File "/home/zidan/Tools/CloudFail/socks.py", line 62, in <module>
>     from collections import Callable
> ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
> ```

Update cloudfail.py as shown here: https://github.com/m0rtem/CloudFail/pull/68/files

But the problem with Callable is still here

**Comment by almostop** [comment]
└─$ python3 cloudfail.py            
Traceback (most recent call last):
  File "/home/kali/Desktop/CloudFail/cloudfail.py", line 9, in <module>
    import socks
  File "/home/kali/Desktop/CloudFail/socks.py", line 62, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
                                                                                                               
anyone please ? i done everything on the internet cant find a solution

**Comment by szyzak** [comment]
> └─$ python3 cloudfail.py Traceback (most recent call last): File "/home/kali/Desktop/CloudFail/cloudfail.py", line 9, in import socks File "/home/kali/Desktop/CloudFail/socks.py", line 62, in from collections import Callable ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/**init**.py)
> 
> anyone please ? i done everything on the internet cant find a solution

In socks.py try changing `from collections import Callable` to `from collections.abc import Callable`

**Comment by almostop** [comment]
i did it didnt work

**Comment by szyzak** [comment]
> To solve problem with Callable, create python 3.8 using update-alternatives, now it works

Tried approach with python 3.8 and I think it managed to work. I've used pyenv aproach [link](https://www.kali.org/docs/general-use/using-eol-python-versions/)

Got python 3.8.13 this way, run again pip install and right now subdomains scan is running.

**Comment by Uraniumhazee** [comment]
> from collections import Callable

hi i solved problem. it works.
I installed python 3.8.13 via your link and this time we need to use only python command not python3! because python command has 3.8.13 :)

When i tried python cloudfail.py --target "asd.com"  i got this error only "
Traceback (most recent call last):
  File "cloudfail.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

pip install -r requirements.txt  this command and errors are

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv                                                             
WARNING: You are using pip version 22.0.4; however, version 22.2 is available.                
You should consider upgrading via the '/root/.pyenv/versions/3.8.13/bin/python3.8 -m pip install --upgrade pip' command.  


So last i used tis command
pip install --upgrade pip    

Now it works :)



python3 = python 3.10
python = python 3.8.13

one more questions if i install python 2.7 how can i use it 
Thanks
