### ISSUE TITLE
error is happening im trying to fiind the origin ip of ixl.com

### ISSUE THREAD

**Issue by WestinFrancis** [m0rtem/CloudFail#69]
here is the error message:
[15:47:35] Initializing CloudFail - the date is: 16/01/2022  
[15:47:35] Fetching initial information from: ixl.com...  
[15:47:35] No ipout file found, fetching data  
[15:47:35] Just checking for updates, please wait...  
[15:47:35] Updating CloudFlare subnet...  
[15:47:35] Updating Crimeflare database...  
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f231dedb978>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f231dedb978>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cloudfail.py", line 309, in <module>
    init(args.target)
  File "cloudfail.py", line 138, in init
    update()
  File "cloudfail.py", line 252, in update
    r = requests.get("http://crimeflare.net:83/domains/ipout.zip", stream=True)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f231dedb978>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by luke13456** [comment]
The code is grabbing data from http://crimeflare.net:83/domains/ipout.zip which is currently down :(

**Comment by WestinFrancis** [comment]
What is the solution?

**Comment by Atif7rbi** [comment]
**- download this file 
http://crimeflare.net:83/domains/ipout.zip 

- unzip it
- 
- copy all files to data folder.  -->> /CloudFail/data/

That's it :)**

**Comment by Atif7rbi** [comment]
> I still keep getting a timeout on http://crimeflare.net:83/domains/ipout.zip when updating the db.
> 
> Error:
> 
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc079bd0d60>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> 
> Any news?

Download from this link 
https://github.com/m0rtem/CloudFail/issues/64#issuecomment-1051120926
