### ISSUE TITLE
Unable to carry out command : sudo python3 cloudfail.py -u

### ISSUE THREAD

**Issue by purplecrow92** [m0rtem/CloudFail#70]
I was not able to carry out command:
$ sudo python3 cloudfail.py -u
due to:
BlockingIOError: [Errno 11] Resource temporarily unavailable

[18:43:31] Initializing CloudFail - the date is: 11/02/2022
[18:43:31] Just checking for updates, please wait...
[18:43:31] Updating CloudFlare subnet...
[18:43:31] Updating Crimeflare database...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7c90fbac40>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c90fbac40>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/purplecrow92/CloudFail/cloudfail.py", line 304, in <module>
    update()
  File "/home/purplecrow92/CloudFail/cloudfail.py", line 252, in update
    r = requests.get("http://crimeflare.net:83/domains/ipout.zip", stream=True)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='crimeflare.net', port=83): Max retries exceeded with url: /domains/ipout.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c90fbac40>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))

**Comment by Teeger5** [comment]
The nature of the problem is similar to https://github.com/m0rtem/CloudFail/issues/24
The fix was to change http://crimeflare.net:82/domains/ipout.zip to http://crimeflare.net:83/domains/ipout.zip
Now the crimeflare.net itself is down
