### ISSUE TITLE
DNS using dnsdumpster Error

### ISSUE THREAD

**Issue by trurrdgr** [m0rtem/CloudFail#73]
[11:37:26] Initializing CloudFail - the date is: 22/06/2022  
[11:37:26] Fetching initial information from: www.xxxx.xx...  
[11:37:26] Server IP: 172.67.71.104  
[11:37:26] Testing if www.amazonweb.vip is on the Cloudflare network...  
[11:37:26] www.amazonweb.vip is part of the Cloudflare network!  
[11:37:26] Testing for misconfigured DNS using dnsdumpster...  
Traceback (most recent call last):
  File "/home/hackgodx/Tools/CloudFail/cloudfail.py", line 307, in <module>
    dnsdumpster(args.target)
  File "/home/hackgodx/Tools/CloudFail/cloudfail.py", line 84, in dnsdumpster
    res = DNSDumpsterAPI(False).search(target)
  File "/home/hackgodx/Tools/CloudFail/DNSDumpsterAPI.py", line 71, in search
    soup = BeautifulSoup(req.content, 'html.parser')
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/usr/local/lib/python3.10/dist-packages/bs4/builder/_htmlparser.py", line 215, in feed
    parser.feed(markup)
  File "/usr/lib/python3.10/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.10/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
  File "/usr/lib/python3.10/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/usr/local/lib/python3.10/dist-packages/bs4/builder/_htmlparser.py", line 160, in handle_decl
    self.soup.endData(Doctype)
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1054, in __getattr__
    return self.find(tag)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1292, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1313, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1610, in __init__
    self.text = self._normalize_search_value(text)
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 1615, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by NoneJobs** [comment]
execute on Linux will be ok

**Comment by NoneJobs** [comment]
in DNSDumpsterAPI.py  add :

`import collections
collections.Callable = collections.abc.Callable`

after :

`import base64`

**Comment by NoneJobs** [comment]
> import collections collections.Callable = collections.abc.Callable

`import collections 
 collections.Callable = collections.abc.Callable`

**Comment by paulobjrr** [comment]
```
import collections
collections.Callable = collections.abc.Callable
```

you might have  been caught by the code syntax here.

Anyway, you save me. Thanks.
