### ISSUE TITLE
cloudfail.py doesnt work 

### ISSUE THREAD

**Issue by almostop** [m0rtem/CloudFail#75]
hey everyone, after i changed lines 180 and 182 like the guides says i got a new error:

└─$ python3 cloudfail.py            
Traceback (most recent call last):
  File "/home/kali/Desktop/CloudFail/cloudfail.py", line 9, in <module>
    import socks
  File "/home/kali/Desktop/CloudFail/socks.py", line 62, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
                                                                                                               
edit: i tried the change in socks.py line 62 from collections to collection.abc didnt worth either

**Comment by almostop** [comment]
still stuck help please

**Comment by mrdenchik** [comment]
@almostop see https://github.com/m0rtem/CloudFail/pull/71/files

**Comment by c4ir0** [comment]
> @almostop see https://github.com/m0rtem/CloudFail/pull/71/files

doesn't help gives another block of errors
