### ISSUE TITLE
SyntaxWarning Error

### ISSUE THREAD

**Issue by Uraniumhazee** [m0rtem/CloudFail#77]
python3 cloudfail.py --target seo.com 

`/root/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/root/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
Traceback (most recent call last):
  File "/root/CloudFail/cloudfail.py", line 9, in <module>
    import socks
  File "/root/CloudFail/socks.py", line 62, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
`

pip3 install -r requirements.txt   results:

`Requirement already satisfied: beautifulsoup4==4.6.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (4.6.0)
Requirement already satisfied: bs4==0.0.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: certifi==2017.4.17 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (2017.4.17)
Requirement already satisfied: chardet==3.0.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (3.0.4)
Requirement already satisfied: colorama==0.3.9 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (0.3.9)
Requirement already satisfied: idna==2.5 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (2.5)
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.27.1)
Requirement already satisfied: urllib3==1.24.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (1.24.2)
Requirement already satisfied: win_inet_pton==1.0.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (1.0.1)
Requirement already satisfied: dnspython==1.15.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 10)) (1.15.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv `

**Comment by Uraniumhazee** [comment]
I fixed it now it is working it needs 3.8.13 python
