### ISSUE TITLE
Callable error

### ISSUE THREAD

**Issue by salman875602** [m0rtem/CloudFail#81]
I can't run tool :(
/home/kali/Desktop/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/kali/Desktop/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/kali/Desktop/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/kali/Desktop/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/kali/Desktop/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
Traceback (most recent call last):
  File "/home/kali/Desktop/CloudFail/cloudfail.py", line 9, in <module>
    import socks
  File "/home/kali/Desktop/CloudFail/socks.py", line 62, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by Fojx** [comment]
Hello, try this
`sed -i 's/from collections import Callable/from collections.abc import Callable/g' socks.py`

**Comment by Lam3rKing** [comment]
i got this:

Traceback (most recent call last):
  File "/home/kali/CloudFail/cloudfail.py", line 17, in <module>
    from DNSDumpsterAPI import DNSDumpsterAPI
  File "/home/kali/CloudFail/DNSDumpsterAPI.py", line 13, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python3.10/dist-packages/bs4/__init__.py", line 35, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python3.10/dist-packages/bs4/builder/__init__.py", line 7, in <module>
    from bs4.element import (
  File "/usr/local/lib/python3.10/dist-packages/bs4/element.py", line 5, in <module>
    import Callable
ModuleNotFoundError: No module named 'Callable'

**Comment by Fojx** [comment]
Hmm, i you have just to edit line 62

Replace this "from collections import Callable"
with this "from collections.abc import Callable"

on file socks.py, but you also have errors about bs4, did you run the installation instructions?
