### ISSUE TITLE
SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by jack3841** [m0rtem/CloudFail#82]
upon running the command, I am getting below errors

python3 cloudfail.py --target seo.com                                  
/home/kali/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/kali/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/kali/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/kali/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/kali/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
Traceback (most recent call last):
  File "/home/kali/CloudFail/cloudfail.py", line 9, in <module>
    import socks
  File "/home/kali/CloudFail/socks.py", line 62, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
~}}

**Comment by benborges** [comment]
Same, on arch, python3, requirements installed fine

**Comment by Fojx** [comment]
what python version are you using ?

**Comment by Aholicknight** [comment]
Having the same error, did anyone find a fix?

**Comment by Fojx** [comment]
Hello, if you are using python3 then you can fix this by with edit **socks.py** file.
You need to change the line **62**
`
Replace this "collections import Callable"
with this "from collections.abc import Callable"
 `
 
But please, remember this is temporary solution, [Zamanry](https://github.com/Zamanry) has an open PR about this, so when this pr will merge you can just pull this changes

**Comment by Aholicknight** [comment]
> Hello, if you are using python3 then you can fix this by with edit **socks.py** file. You need to change the line **62**
> 
> Replace this `"from collections import Callable"` with this `"from collections.abc import Callable"`

@Fojx Thank you for your comment. After some time tinkering around, it now works, even with GitHub actions.
