### ISSUE TITLE
File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn

### ISSUE THREAD

**Issue by markleeit** [m0rtem/CloudFail#86]
I try it, but it not working.
Python3 is version 3.10.5
My command: `python3 CloudFail.py -t 'bitbns.com'`
How fix?
```

[16:38:21] Initializing CloudFail - the date is: 07/09/2022  
[16:38:21] Fetching initial information from: bitbns.com...  
[16:38:21] No ipout file found, fetching data  
[16:38:21] Just checking for updates, please wait...  
[16:38:21] Updating CloudFlare subnet...  
[16:38:21] Updating Crimeflare database...  
Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbe7288e7a0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/kali/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cf.ozeliurs.com', port=443): Max retries exceeded with url: /ipout (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe7288e7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/CloudFail/cloudfail.py", line 304, in <module>
    init(args.target)
  File "/home/kali/CloudFail/cloudfail.py", line 138, in init
    update()
  File "/home/kali/CloudFail/cloudfail.py", line 252, in update
    r = requests.get("https://cf.ozeliurs.com/ipout", stream=True)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cf.ozeliurs.com', port=443): Max retries exceeded with url: /ipout (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbe7288e7a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by slypy** [comment]
same here

**Comment by dol0han** [comment]
yeah whats up with this? I keep hearing how great this is but I got a TON of exceptions over here, I don't know much but I know thius aint right. help please? I changed socks.py to connections.abc: and got these errors

/home/nate/gitClone/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/nate/gitClone/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/nate/gitClone/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/nate/gitClone/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while choice is not 'y' and choice is not 'n':
/home/nate/gitClone/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if choice is 'y':
   ____ _                 _ _____     _ _
  / ___| | ___  _   _  __| |  ___|_ _(_) |
 | |   | |/ _ \| | | |/ _` | |_ / _` | | |
 | |___| | (_) | |_| | (_| |  _| (_| | | |
  \____|_|\___/ \__,_|\__,_|_|  \__,_|_|_|
    v1.0.4                      by m0rtem


[13:59:34] Initializing CloudFail - the date is: 11/09/2022  
Traceback (most recent call last):
  File "/home/nate/gitClone/CloudFail/socks.py", line 729, in connect
    _BaseSocket.connect(self, proxy_addr)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
  File "/home/nate/gitClone/CloudFail/socks.py", line 740, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fca8d07d1b0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/home/nate/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca8d07d1b0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/gitClone/CloudFail/cloudfail.py", line 288, in <module>
    tor_ip = requests.get(ipcheck_url)
  File "/home/nate/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/nate/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/nate/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nate/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/nate/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca8d07d1b0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/gitClone/CloudFail/cloudfail.py", line 295, in <module>
    print(e, net_exc)
NameError: name 'net_exc' is not defined'''

**Comment by slypy** [comment]
> yeah whats up with this? I keep hearing how great this is but I got a TON of exceptions over here, I don't know much but I know thius aint right. help please? I changed socks.py to connections.abc: and got these errors
> 
> /home/nate/gitClone/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="? while choice is not 'y' and choice is not 'n': /home/nate/gitClone/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="? while choice is not 'y' and choice is not 'n': /home/nate/gitClone/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="? while choice is not 'y' and choice is not 'n': /home/nate/gitClone/CloudFail/cloudfail.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="? while choice is not 'y' and choice is not 'n': /home/nate/gitClone/CloudFail/cloudfail.py:182: SyntaxWarning: "is" with a literal. Did you mean "=="? if choice is 'y':
> 
> / ___| | ___ _ _ __| | **_|_ _(_) | | | | |/ _ | | | |/ _` | |_ / _` | | | | |_**| | (_) | |_| | (_| | _| (_| | | | _**_|_|_**/ __,_|__,_|_| __,_|_|_| v1.0.4 by m0rtem
> 
> [13:59:34] Initializing CloudFail - the date is: 11/09/2022 Traceback (most recent call last): File "/home/nate/gitClone/CloudFail/socks.py", line 729, in connect _BaseSocket.connect(self, proxy_addr) ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connection.py", line 158, in _new_conn conn = connection.create_connection( File "/home/nate/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 80, in create_connection raise err File "/home/nate/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 70, in create_connection sock.connect(sa) File "/home/nate/gitClone/CloudFail/socks.py", line 740, in connect raise ProxyConnectionError(msg, error) socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 597, in urlopen httplib_response = self._make_request(conn, method, url, File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 354, in _make_request conn.request(method, url, **httplib_request_kw) File "/usr/lib/python3.10/http/client.py", line 1282, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output self.send(msg) File "/usr/lib/python3.10/http/client.py", line 975, in send self.connect() File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connection.py", line 181, in connect conn = self._new_conn() File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connection.py", line 167, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fca8d07d1b0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/nate/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/home/nate/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 637, in urlopen retries = retries.increment(method, url, error=e, _pool=self, File "/home/nate/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 399, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca8d07d1b0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/nate/gitClone/CloudFail/cloudfail.py", line 288, in tor_ip = requests.get(ipcheck_url) File "/home/nate/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get return request("get", url, params=params, **kwargs) File "/home/nate/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "/home/nate/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/home/nate/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/home/nate/.local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca8d07d1b0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/nate/gitClone/CloudFail/cloudfail.py", line 295, in print(e, net_exc) NameError: name 'net_exc' is not defined'''

that warnings are fine, take a look at to my forked repository [click here](https://github.com/slypy/CloudFail-fix-version).

**Comment by m0rtem** [comment]
Looks like you are trying to run with TOR but you do not have TOR installed. Please check to see if you have SOCKS5 TOR service running on PORT 9050 before you try to use it with TOR.
