### ISSUE TITLE
PermissionError:[Errno 13] 

### ISSUE THREAD

**Issue by tabibit0** [m0rtem/CloudFail#87]
Hi, I'm getting this one please help:

Traceback (most recent call last):
  File "/home/CloudFail/cloudfail.py", line 304, in <module>
    init(args.target)
  File "/home/CloudFail/cloudfail.py", line 138, in init
    update()
  File "/home/CloudFail/cloudfail.py", line 246, in update
    with open('data/cf-subnet.txt', 'wb') as fd:
PermissionError: [Errno 13] Permission denied: 'data/cf-subnet.txt'

Thank you

**Comment by slypy** [comment]
> Hi, I'm getting this one please help:
> 
> Traceback (most recent call last): File "/home/CloudFail/cloudfail.py", line 304, in init(args.target) File "/home/CloudFail/cloudfail.py", line 138, in init update() File "/home/CloudFail/cloudfail.py", line 246, in update with open('data/cf-subnet.txt', 'wb') as fd: PermissionError: [Errno 13] Permission denied: 'data/cf-subnet.txt'
> 
> Thank you

Hello, friend. Did you run this with `sudo`?
