### ISSUE TITLE
cloudfail.py error line 118 and 310 

### ISSUE THREAD

**Issue by falcosmash** [m0rtem/CloudFail#96]
Hi everyone,

While launching python3 cloudfail.py --target something.com I get this error 

Traceback (most recent call last):
 File "/home/kali/git/CloudFail/cloudfail.py", line 310, in <module> 
     crimeflare(args.target)
  File "/home/kali/git/CloudFail/cloudfail.py", line 118, in crimeflare
    if lineExploded[1] = args.target: 
IndexError: list of index out of range

Thanks in advance for your help

**Comment by cimsz** [comment]
I have the same issue

**Comment by Zavada-Nazarii** [comment]
also faced this

**Comment by AtishaAkashi** [comment]
Hi,did you solve the issue?

**Comment by Zavada-Nazarii** [comment]
> Hi,did you solve the issue?

Hi, unfortunately, I put this tool aside now, I didn't have more time to look for a solution.
